// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public final class Chain {
  private Chain() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_HeadStateUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_HeadStateUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_TailStateUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_TailStateUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_LatestXidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_LatestXidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_LatestXidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_LatestXidResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_HeadStateTransferRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_HeadStateTransferRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_HeadStateTransferRequest_StateEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_HeadStateTransferRequest_StateEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_TailStateTransferRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_TailStateTransferRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_TailStateTransferRequest_StateEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_TailStateTransferRequest_StateEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_ChainResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_ChainResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_IncrementRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_IncrementRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_TailIncrementRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_TailIncrementRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_TailDeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_TailDeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_HeadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_HeadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_XidProcessedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_XidProcessedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_CxidProcessedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_CxidProcessedRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013chain.proto\022\003adb\"N\n\026HeadStateUpdateReq" +
      "uest\022\013\n\003src\030\001 \001(\004\022\013\n\003xid\030\002 \001(\004\022\013\n\003key\030\003 " +
      "\001(\t\022\r\n\005value\030\004 \001(\005\"x\n\026TailStateUpdateReq" +
      "uest\022\013\n\003src\030\001 \001(\004\022\013\n\003xid\030\002 \001(\004\022\013\n\003key\030\003 " +
      "\001(\t\022\r\n\005value\030\004 \001(\005\022\014\n\004host\030\005 \001(\t\022\014\n\004port" +
      "\030\006 \001(\005\022\014\n\004cxid\030\007 \001(\005\"\022\n\020LatestXidRequest" +
      "\",\n\021LatestXidResponse\022\n\n\002rc\030\001 \001(\r\022\013\n\003xid" +
      "\030\002 \001(\004\"\313\001\n\030HeadStateTransferRequest\022\013\n\003s" +
      "rc\030\001 \001(\004\022\020\n\010stateXid\030\002 \001(\004\0227\n\005state\030\003 \003(" +
      "\0132(.adb.HeadStateTransferRequest.StateEn" +
      "try\022)\n\004sent\030\004 \003(\0132\033.adb.HeadStateUpdateR" +
      "equest\032,\n\nStateEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\005:\0028\001\"\313\001\n\030TailStateTransferReques" +
      "t\022\013\n\003src\030\001 \001(\004\022\020\n\010stateXid\030\002 \001(\004\0227\n\005stat" +
      "e\030\003 \003(\0132(.adb.TailStateTransferRequest.S" +
      "tateEntry\022)\n\004sent\030\004 \003(\0132\033.adb.TailStateU" +
      "pdateRequest\032,\n\nStateEntry\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\005:\0028\001\"\033\n\rChainResponse\022\n\n\002r" +
      "c\030\001 \001(\r\"2\n\020IncrementRequest\022\013\n\003key\030\001 \001(\t" +
      "\022\021\n\tincrValue\030\002 \001(\005\"\034\n\rDeleteRequest\022\013\n\003" +
      "key\030\001 \001(\t\"`\n\024TailIncrementRequest\022\013\n\003key" +
      "\030\001 \001(\t\022\021\n\tincrValue\030\002 \001(\005\022\014\n\004host\030\003 \001(\t\022" +
      "\014\n\004port\030\004 \001(\005\022\014\n\004cxid\030\005 \001(\005\"J\n\021TailDelet" +
      "eRequest\022\013\n\003key\030\001 \001(\t\022\014\n\004host\030\002 \001(\t\022\014\n\004p" +
      "ort\030\003 \001(\005\022\014\n\004cxid\030\004 \001(\005\"\032\n\014HeadResponse\022" +
      "\n\n\002rc\030\001 \001(\r\"\031\n\nGetRequest\022\013\n\003key\030\001 \001(\t\"(" +
      "\n\013GetResponse\022\n\n\002rc\030\001 \001(\r\022\r\n\005value\030\002 \001(\005" +
      "\"\"\n\023XidProcessedRequest\022\013\n\003xid\030\001 \001(\004\"$\n\024" +
      "CxidProcessedRequest\022\014\n\004cxid\030\001 \001(\0052\254\003\n\020H" +
      "eadChainReplica\022E\n\022proposeStateUpdate\022\033." +
      "adb.HeadStateUpdateRequest\032\022.adb.ChainRe" +
      "sponse\022=\n\014getLatestXid\022\025.adb.LatestXidRe" +
      "quest\032\026.adb.LatestXidResponse\022B\n\rstateTr" +
      "ansfer\022\035.adb.HeadStateTransferRequest\032\022." +
      "adb.ChainResponse\0225\n\tincrement\022\025.adb.Inc" +
      "rementRequest\032\021.adb.HeadResponse\022/\n\006dele" +
      "te\022\022.adb.DeleteRequest\032\021.adb.HeadRespons" +
      "e\022(\n\003get\022\017.adb.GetRequest\032\020.adb.GetRespo" +
      "nse\022<\n\014xidProcessed\022\030.adb.XidProcessedRe" +
      "quest\032\022.adb.ChainResponse2\366\002\n\020TailChainR" +
      "eplica\022E\n\022proposeStateUpdate\022\033.adb.TailS" +
      "tateUpdateRequest\032\022.adb.ChainResponse\022=\n" +
      "\014getLatestXid\022\025.adb.LatestXidRequest\032\026.a" +
      "db.LatestXidResponse\022B\n\rstateTransfer\022\035." +
      "adb.TailStateTransferRequest\032\022.adb.Chain" +
      "Response\0229\n\tincrement\022\031.adb.TailIncremen" +
      "tRequest\032\021.adb.HeadResponse\0223\n\006delete\022\026." +
      "adb.TailDeleteRequest\032\021.adb.HeadResponse" +
      "\022(\n\003get\022\017.adb.GetRequest\032\020.adb.GetRespon" +
      "se2L\n\nTailClient\022>\n\rcxidProcessed\022\031.adb." +
      "CxidProcessedRequest\032\022.adb.ChainResponse" +
      "B\030\n\024edu.sjsu.cs249.chainP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_adb_HeadStateUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_adb_HeadStateUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_HeadStateUpdateRequest_descriptor,
        new java.lang.String[] { "Src", "Xid", "Key", "Value", });
    internal_static_adb_TailStateUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_adb_TailStateUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_TailStateUpdateRequest_descriptor,
        new java.lang.String[] { "Src", "Xid", "Key", "Value", "Host", "Port", "Cxid", });
    internal_static_adb_LatestXidRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_adb_LatestXidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_LatestXidRequest_descriptor,
        new java.lang.String[] { });
    internal_static_adb_LatestXidResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_adb_LatestXidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_LatestXidResponse_descriptor,
        new java.lang.String[] { "Rc", "Xid", });
    internal_static_adb_HeadStateTransferRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_adb_HeadStateTransferRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_HeadStateTransferRequest_descriptor,
        new java.lang.String[] { "Src", "StateXid", "State", "Sent", });
    internal_static_adb_HeadStateTransferRequest_StateEntry_descriptor =
      internal_static_adb_HeadStateTransferRequest_descriptor.getNestedTypes().get(0);
    internal_static_adb_HeadStateTransferRequest_StateEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_HeadStateTransferRequest_StateEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_adb_TailStateTransferRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_adb_TailStateTransferRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_TailStateTransferRequest_descriptor,
        new java.lang.String[] { "Src", "StateXid", "State", "Sent", });
    internal_static_adb_TailStateTransferRequest_StateEntry_descriptor =
      internal_static_adb_TailStateTransferRequest_descriptor.getNestedTypes().get(0);
    internal_static_adb_TailStateTransferRequest_StateEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_TailStateTransferRequest_StateEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_adb_ChainResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_adb_ChainResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_ChainResponse_descriptor,
        new java.lang.String[] { "Rc", });
    internal_static_adb_IncrementRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_adb_IncrementRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_IncrementRequest_descriptor,
        new java.lang.String[] { "Key", "IncrValue", });
    internal_static_adb_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_adb_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_DeleteRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_adb_TailIncrementRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_adb_TailIncrementRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_TailIncrementRequest_descriptor,
        new java.lang.String[] { "Key", "IncrValue", "Host", "Port", "Cxid", });
    internal_static_adb_TailDeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_adb_TailDeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_TailDeleteRequest_descriptor,
        new java.lang.String[] { "Key", "Host", "Port", "Cxid", });
    internal_static_adb_HeadResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_adb_HeadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_HeadResponse_descriptor,
        new java.lang.String[] { "Rc", });
    internal_static_adb_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_adb_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_GetRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_adb_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_adb_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_GetResponse_descriptor,
        new java.lang.String[] { "Rc", "Value", });
    internal_static_adb_XidProcessedRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_adb_XidProcessedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_XidProcessedRequest_descriptor,
        new java.lang.String[] { "Xid", });
    internal_static_adb_CxidProcessedRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_adb_CxidProcessedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_CxidProcessedRequest_descriptor,
        new java.lang.String[] { "Cxid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
