// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public interface ChainResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adb.ChainResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * rc = 0 means success, rc = 1 you shouldn't be talking to me
   * </pre>
   *
   * <code>uint32 rc = 1;</code>
   */
  int getRc();
}
