// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public interface CxidProcessedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adb.CxidProcessedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 cxid = 1;</code>
   */
  int getCxid();
}
