// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public interface DeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adb.DeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * if the key does not exist, the delete will still be successful
   * </pre>
   *
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <pre>
   * if the key does not exist, the delete will still be successful
   * </pre>
   *
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
