// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public interface HeadStateUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adb.HeadStateUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 src = 1;</code>
   */
  long getSrc();

  /**
   * <code>uint64 xid = 2;</code>
   */
  long getXid();

  /**
   * <code>string key = 3;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 3;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>int32 value = 4;</code>
   */
  int getValue();
}
