// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public interface LatestXidRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adb.LatestXidRequest)
    com.google.protobuf.MessageOrBuilder {
}
