// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public interface TailDeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adb.TailDeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * if the key does not exist, the delete will still be successful
   * </pre>
   *
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <pre>
   * if the key does not exist, the delete will still be successful
   * </pre>
   *
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string host = 2;</code>
   */
  java.lang.String getHost();
  /**
   * <code>string host = 2;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 port = 3;</code>
   */
  int getPort();

  /**
   * <code>int32 cxid = 4;</code>
   */
  int getCxid();
}
