// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public interface TailIncrementRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adb.TailIncrementRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <pre>
   * if the key does not exist, it will be created with this value, otherwise the value
   * if the existing key will be incremented by this value
   * </pre>
   *
   * <code>int32 incrValue = 2;</code>
   */
  int getIncrValue();

  /**
   * <code>string host = 3;</code>
   */
  java.lang.String getHost();
  /**
   * <code>string host = 3;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 port = 4;</code>
   */
  int getPort();

  /**
   * <code>int32 cxid = 5;</code>
   */
  int getCxid();
}
