// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chain.proto

package edu.sjsu.cs249.chain;

public interface XidProcessedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adb.XidProcessedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 xid = 1;</code>
   */
  long getXid();
}
